sudo: required
language: cpp
compiler:
  - clang

addons:
  apt:
    sources:
    - llvm-toolchain-precise
    packages:
    - clang-3.8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ninja python-pip python-dev build-essential
  - sudo pip install --upgrade pip
  - sudo pip install meson

install:
  - export CXX="clang++-3.7" CC="clang-3.7"; fi

script:
  - mkdir build
  - meson build
  - cd build
  - ninja
  - ninja test
