sudo: required
language: cpp
compiler:
  - clang

addons:
  apt:
    sources:
    - llvm-toolchain-precise
    packages:
    - clang-3.8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ninja python3-pip python-dev build-essential libpulse-dev
  - sudo pip3 install --upgrade pip
  - sudo pip3 install meson

install:
  - export CXX="clang++" CC="clang"

script:
  - mkdir build
  - meson build
  - cd build
  - sudo ninja
